#! /bin/bash

/home/yketa/miniconda3/bin/python3.6 <<EOF

import sys
import pickle

param = {'N':0, 'a':1, 'pdi':2, 'N_sizes':3, 'density':4, 'box_size':5, 'kT':6, 'mu':7, 'k':8, 'vzero':9, 'dr':10, 'damp_bro':11, 'shear_rate':12, 'time_step':13, 'N_steps':14, 'period_dump':15, 'prep_steps':16}

if not('$2'  in param):
	print("There is no parameter '$2'")
	sys.exit()

with open('/home/yketa/hoomd/colmig_DPD_P_A/data/$1/param.pickle', 'rb') as param_file:
	data = pickle.load(param_file)

print("%e" % data[param['$2']])

EOF

