#! /home/yketa/miniconda3/bin/python3.6

import os
import sys

import numpy as np

import pickle

sys.path.append('/home/yketa')
from exponents import float_to_letters

data_dir = os.environ['DATA_DIRECTORY'] if 'DATA_DIRECTORY' in os.environ else os.getcwd() # data directory
parameters_file = os.environ['PARAMETERS_FILE'] if 'PARAMETERS_FILE' in os.environ else data_dir + '/param.pickle' # parameters file

dis_time = int(eval(os.environ['TIME'])) if 'TIME' in os.environ else -1 # time interval for the displacement

init_frame = int(eval(os.environ['INITIAL_FRAME'])) if 'INITIAL_FRAME' in os.environ else -1 # initial time for the calculation of the displacement correlation
int_max = int(eval(os.environ['INTERVAL_MAXIMUM'])) if 'INTERVAL_MAXIMUM' in os.environ else 1 # maximum number of intervals taken for the calculation of the displacement correlation
Ncases = int(eval(os.environ['N_CASES'])) if 'N_CASES' in os.environ else int(np.sqrt(N)) + (1 - int(np.sqrt(N))%2) # number of cases in each direction to compute the velocity grid

with open(parameters_file, 'rb') as param_file:
	N, a, pdi, N_sizes, density, box_size, kT, mu, k, vzero, dr, damp_bro, shear_rate, time_step, N_steps, period_dump, prep_steps = pickle.load(param_file)

Nentries = N_steps//period_dump # number of time snapshots in velocity and position files
init_frame = int(Nentries/2) if init_frame < 0 else init_frame # initial frame
Nframes = Nentries - init_frame # number of frames available for the calculation

dis_time = Nframes + dis_time if dis_time <= 0 else dis_time # length of the interval of time for which the correlation displacement is calculated

fname = lambda var: data_dir + '/' + var + str('_D%s_V%s_R%s_N%s_I%s_T%s_M%s_C%s' % tuple(map(float_to_letters, [density, vzero, dr, N, init_frame, dis_time, int_max, Ncases]))) # Cuu file name
Cuu_file_name = os.environ['CUU_FILE'] if 'CUU_FILE' in os.environ else fname('Cuu') + '.pickle' # Cuu file name
Cnn_file_name = os.environ['CNN_FILE'] if 'CNN_FILE' in os.environ else fname('Cnn') + '.pickle' # Cnn file name

with open(Cuu_file_name, 'rb') as Cuu_file, open(Cnn_file_name, 'rb') as Cnn_file:
	Cuu2D, Cuu1D, Cuu1Dcor = pickle.load(Cuu_file)
	Cnn2D, Cnn1D = pickle.load(Cnn_file)

# PLOT

# plot parameters

Cuu_min = float(eval(os.environ['CUU_MIN'])) if 'CUU_MIN' in os.environ else 1e-3
r_min = float(eval(os.environ['R_MIN'])) if 'R_MIN' in os.environ else 1
r_max = float(eval(os.environ['R_MAX'])) if 'R_MAX' in os.environ else 20

plot_axis = os.environ['AXIS'] if 'AXIS' in os.environ else 'LOGLOG'
fplot = lambda ax: ax.loglog if plot_axis == 'LOGLOG' else ax.semilogy if plot_axis == 'LINLOG' else ax.semilogx if plot_axis == 'LOGLIN' else ax.plot

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import matplotlib.cm as cmx
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.gridspec import GridSpec

cmap = plt.cm.jet
fig, axs = plt.subplots(2, 2)

fig.set_size_inches(16, 16)
fig.subplots_adjust(wspace=0.3)
fig.subplots_adjust(hspace=0.3)

fig.suptitle(r'$N=%.2e, \phi=%1.2f, \tilde{v}=%.2e, \tilde{\nu}_r=%.2e$' % (N, density, vzero, dr) + '\n' + r'$S_{init}=%.2e, \Delta t=%.2e, S_{max}=%.2e, N_{cases}=%.2e$' % (init_frame, dis_time*period_dump*time_step, int_max, Ncases))

# Cuu

Cuumin = 0 if np.min(Cuu2D) > 0 else np.min(Cuu2D)
Cuumax = np.max(Cuu2D)

CuuvNorm = colors.Normalize(vmin=Cuumin, vmax=Cuumax)
CuuscalarMap = cmx.ScalarMappable(norm=CuuvNorm, cmap=cmap) 

axs[0, 0].imshow(np.roll(np.roll(Cuu2D, int(Ncases/2), axis=0), int(Ncases/2), axis=1), cmap=cmap, norm=CuuvNorm)

axs[0, 0].set_xlabel(r'$x$')
axs[0, 0].set_ylabel(r'$y$')
axs[0, 0].set_title('2D ' + r'$C_{uu}$')

divider = make_axes_locatable(axs[0, 0])
cax = divider.append_axes("right", size="5%", pad=0.05)
cb = mpl.colorbar.ColorbarBase(cax, cmap=cmap, norm=CuuvNorm, orientation='vertical')

fplot(axs[1, 0])(Cuu1D[1:, 0], Cuu1D[1:, 1]/Cnn1D[-1, 1])

axs[1, 0].set_xlabel(r'$r$')
axs[1, 0].set_ylabel(r'$C_{uu}/C_{\rho\rho}(r=r_{max})$')
axs[1, 0].set_title('radial ' + r'$C_{uu}/C_{\rho\rho}(r=r_{max})$' + ' ' + r'$(C_{\rho\rho}(r=r_{max}) = %.3e)$' % Cnn1D[-1, 1])

axs[1, 0].set_xlim(r_min, r_max)
axs[1, 0].set_ylim(Cuu_min, 1)

# Cnn

axs[0, 1].plot(Cnn1D[1:, 0], Cnn1D[1:, 1])

axs[0, 1].set_xlabel(r'$r$')
axs[0, 1].set_ylabel(r'$C_{\rho\rho}$')
axs[0, 1].set_title('radial ' + r'$C_{\rho\rho}$')

axs[0, 1].set_xlim(r_min, r_max)

fplot(axs[1, 1])(Cuu1Dcor[1:, 0], Cuu1Dcor[1:, 1])

axs[1, 1].set_xlabel(r'$r$')
axs[1, 1].set_ylabel(r'$C_{uu}/C_{\rho\rho}$')
axs[1, 1].set_title('radial ' + r'$C_{uu}/C_{\rho\rho}$')

axs[1, 1].set_xlim(r_min, r_max)
axs[1, 1].set_ylim(Cuu_min, 1)

if 'SAVE' in os.environ and eval(os.environ['SAVE']):
	plt.savefig(fname('Cuu') + '_' + plot_axis + '.eps') # saving the figure
	print('Figure saved as \'' + fname('Cuu') + '_' + plot_axis + '.eps\'')

if 'SHOW' in os.environ and eval(os.environ['SHOW']):
	plt.show() # showing the figure
